---
apiVersion: v1
kind: Service
metadata:
  namespace: hashicups
  name: payments
spec:
  selector:
    app: payments
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: hashicups
  name: payments
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hashicups
  name: payments
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      serviceAccountName: payments
      containers:
        - name: payments
          image: hashicorpdemoapp/payments:v0.0.12
          imagePullPolicy: Always
          ports:
            - containerPort: 8080